<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="HksFuncGenerator/**/*.cs" />
    <Compile Remove="HksScript.Sdk/**/*.cs" />
  </ItemGroup>

  <Target Name="CopySdk" AfterTargets="Build">
    <Copy SourceFiles="HksScript.Sdk/bin/$(Configuration)/netstandard2.0/HksScript.Sdk.dll" DestinationFolder="$(OutputPath)" Condition="Exists('HksScript.Sdk/bin/$(Configuration)/netstandard2.0/HksScript.Sdk.dll')" />
  </Target>

  <Target Name="BuildGenerator" BeforeTargets="CoreCompile">
    <MSBuild Projects="HksFuncGenerator/HksFuncGenerator.csproj" Targets="Build" Properties="Configuration=$(Configuration)" />
  </Target>

  <ItemGroup>
    <Analyzer Include="HksFuncGenerator/bin/$(Configuration)/netstandard2.0/HksFuncGenerator.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="OpenCvSharp5" Version="5.0.0.20260721" />
    <PackageReference Include="OpenCvSharp5.official.runtime.linux-x64" Version="5.0.0.20260721" />
  </ItemGroup>

</Project>
