using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HksFuncGenerator;

[Generator]
public class HksFuncGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilation = context.CompilationProvider;

        var methodInfos = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is MethodDeclarationSyntax,
            transform: GetMethodInfo)
            .Where(m => m != null);

        var typeInfos = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is TypeDeclarationSyntax,
            transform: GetTypeInfo)
            .Where(t => t != null);

        var combined = methodInfos.Collect().Combine(typeInfos.Collect()).Combine(compilation);

        context.RegisterSourceOutput(combined, (spc, source) =>
        {
            var ((methods, types), comp) = source;
            var mList = methods.Where(m => m != null).Select(m => m!).ToList();
            var tList = types.Where(t => t != null).Select(t => t!).ToList();
            if (mList.Count == 0 && tList.Count == 0) return;

            var hasFunctionTable = comp.GetTypeByMetadataName("HksScript.Interpreter.FunctionTable") != null;
            var registry = GenerateRegistry(mList, tList, hasFunctionTable);
            if (!string.IsNullOrEmpty(registry))
                spc.AddSource("HksFuncRegistry.g.cs", registry);
        });
    }

    private static MethodInfo? GetMethodInfo(GeneratorSyntaxContext ctx, System.Threading.CancellationToken _)
    {
        var method = (MethodDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(method);
        if (symbol == null) return null;

        var attr = symbol.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name.Contains("HksFunc") == true);
        if (attr == null) return null;

        var alias = "";
        if (attr.NamedArguments.Length > 0)
            alias = attr.NamedArguments[0].Value.Value?.ToString() ?? "";

        var isInstance = !symbol.IsStatic;
        var paramTypes = symbol.Parameters.Select(p => MapType(p.Type)).ToArray();
        // 实例方法：第一个参数为声明类型
        if (isInstance)
            paramTypes = new[] { MapType(symbol.ContainingType) }.Concat(paramTypes).ToArray();

        var returnType = MapType(symbol.ReturnType);
        var scriptName = !string.IsNullOrEmpty(alias) ? alias : ToSnakeCase(symbol.Name);
        var fullType = symbol.ContainingType.ToDisplayString();

        return new MethodInfo(scriptName, fullType, symbol.Name, paramTypes, returnType, isInstance);
    }

    private static TypeInfo? GetTypeInfo(GeneratorSyntaxContext ctx, System.Threading.CancellationToken _)
    {
        var typeDecl = (TypeDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(typeDecl);
        if (symbol == null) return null;

        var attr = symbol.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name.Contains("HksType") == true);
        if (attr == null) return null;

        var alias = "";
        if (attr.NamedArguments.Length > 0)
            alias = attr.NamedArguments[0].Value.Value?.ToString() ?? "";

        var typeName = !string.IsNullOrEmpty(alias) ? alias : ToSnakeCase(symbol.Name);
        var fullName = symbol.ToDisplayString();

        // 收集公共字段
        var fields = symbol.GetMembers().Where(m => m is IFieldSymbol f && f.DeclaredAccessibility == Accessibility.Public && !f.IsStatic)
            .Select(m => (IFieldSymbol)m)
            .Select(f => new FieldInfo(f.Name, MapType(f.Type)))
            .ToList();

        // 收集构造器
        var ctors = symbol.Constructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public)
            .Select(c => new CtorInfo(c.Parameters.Select(p => MapType(p.Type)).ToArray()))
            .ToList();

        return new TypeInfo(typeName, fullName, ctors, fields);
    }

    private static string MapType(ITypeSymbol type)
    {
        var name = type.ToDisplayString();
        return name switch
        {
            "int" => "int",
            "double" or "float" => "float",
            "string" => "string",
            "bool" => "bool",
            "void" => "void",
            _ when name.Contains("List<") => "Set<" + ExtractGenericArg(name) + ">",
            _ => name
        };
    }

    private static string GenerateRegistry(List<MethodInfo> methods, List<TypeInfo> types, bool hasFunctionTable)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");

        if (hasFunctionTable)
        {
            sb.AppendLine("using HksScript.Interpreter;");
            sb.AppendLine();
            sb.AppendLine("public static partial class HksFuncRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    public static void RegisterAll(FunctionTable table)");
            sb.AppendLine("    {");

            foreach (var m in methods)
            {
                var methodName = m.MethodName;
                var tail = "";
                var casts = m.ParamTypes.Select((p, i) => $"({p})args[{i}]").ToList();

                if (m.IsInstance)
                {
                    var instanceCast = $"({m.ParamTypes[0]})args[0]";
                    var restArgs = string.Join(", ", casts.Skip(1));
                    tail = $"{instanceCast}.{methodName}({restArgs})";
                }
                else
                {
                    tail = $"{m.FullType}.{methodName}({string.Join(", ", casts)})";
                }

                if (m.ReturnType == "void")
                    sb.AppendLine($"        table.Register(\"{m.ScriptName}\", new ExternalFunction(\"{m.ScriptName}\", args => {{ {tail}; return null; }}));");
                else
                    sb.AppendLine($"        table.Register(\"{m.ScriptName}\", new ExternalFunction(\"{m.ScriptName}\", args => (object?){tail}));");
            }

            foreach (var t in types)
            {
                // 构造器
                foreach (var c in t.Constructors)
                {
                    var args = string.Join(", ", c.ParamTypes.Select((p, i) => $"({p})args[{i}]"));
                    var ctorCall = string.IsNullOrEmpty(args) ? "" : ", " + args;
                    sb.AppendLine($"        table.Register(\"{t.TypeName}\", new ExternalFunction(\"{t.TypeName}\", args => Activator.CreateInstance(typeof({t.FullName}){ctorCall})!));");
                }

                // 字段读写器
                foreach (var f in t.Fields)
                {
                    var fieldOf = $"typeof({t.FullName}).GetField(\"{f.Name}\", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance)!";
                    sb.AppendLine($"        table.Register(\"{t.TypeName}_get_{f.Name}\", new ExternalFunction(\"{t.TypeName}_get_{f.Name}\", args => {fieldOf}.GetValue(args[0])));");
                    sb.AppendLine($"        table.Register(\"{t.TypeName}_set_{f.Name}\", new ExternalFunction(\"{t.TypeName}_set_{f.Name}\", args => {{ {fieldOf}.SetValue(args[0], ({f.Type})args[1]!); return null; }}));");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine();
            sb.AppendLine("// [HksFunc] / [HksType] found — use 'hks install' for runtime discovery");
            sb.AppendLine($"// Methods: {methods.Count}, Types: {types.Count}");
            if (methods.Count > 0)
                sb.AppendLine($"// Functions: {string.Join(", ", methods.Select(m => m.ScriptName))}");
            if (types.Count > 0)
                sb.AppendLine($"// Types: {string.Join(", ", types.Select(t => t.TypeName))}");
        }

        return sb.ToString();
    }

    private static string ToSnakeCase(string name)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            if (i > 0 && char.IsUpper(name[i]))
                sb.Append('_');
            sb.Append(char.ToLower(name[i]));
        }
        return sb.ToString();
    }

    private static string ExtractGenericArg(string type)
    {
        var start = type.IndexOf('<');
        var end = type.LastIndexOf('>');
        return start >= 0 && end > start ? type.Substring(start + 1, end - start - 1) : type;
    }

    private class MethodInfo
    {
        public string ScriptName { get; }
        public string FullType { get; }
        public string MethodName { get; }
        public string[] ParamTypes { get; }
        public string ReturnType { get; }
        public bool IsInstance { get; }
        public MethodInfo(string s, string t, string m, string[] p, string r, bool isInst = false)
        { ScriptName = s; FullType = t; MethodName = m; ParamTypes = p; ReturnType = r; IsInstance = isInst; }
    }
    private class CtorInfo
    {
        public string[] ParamTypes { get; }
        public CtorInfo(string[] p) { ParamTypes = p; }
    }
    private class FieldInfo
    {
        public string Name { get; }
        public string Type { get; }
        public FieldInfo(string n, string t) { Name = n; Type = t; }
    }
    private class TypeInfo
    {
        public string TypeName { get; }
        public string FullName { get; }
        public List<CtorInfo> Constructors { get; }
        public List<FieldInfo> Fields { get; }
        public TypeInfo(string tn, string fn, List<CtorInfo> c, List<FieldInfo> f)
        { TypeName = tn; FullName = fn; Constructors = c; Fields = f; }
    }
}
