using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HksFuncGenerator;

[Generator]
public class HksFuncGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: (node, _) => node is MethodDeclarationSyntax,
            transform: GetMethodInfo)
            .Where(m => m != null);

        var combined = methods.Collect();

        context.RegisterSourceOutput(combined, (spc, source) =>
        {
            var list = source.Where(m => m != null).Select(m => m!).ToList();
            var registry = GenerateRegistry(list);
            if (!string.IsNullOrEmpty(registry))
                spc.AddSource("HksFuncRegistry.g.cs", registry);
        });
    }

    private static MethodInfo? GetMethodInfo(GeneratorSyntaxContext ctx, System.Threading.CancellationToken _)
    {
        var method = (MethodDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(method);
        if (symbol == null) return null;

        var attr = symbol.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.Name.Contains("HksFunc") == true);
        if (attr == null) return null;

        var alias = "";
        if (attr.NamedArguments.Length > 0)
            alias = attr.NamedArguments[0].Value.Value?.ToString() ?? "";

        var paramTypes = symbol.Parameters.Select(p => MapType(p.Type)).ToArray();
        var returnType = MapType(symbol.ReturnType);
        var scriptName = !string.IsNullOrEmpty(alias) ? alias : ToSnakeCase(symbol.Name);
        var fullType = symbol.ContainingType.ToDisplayString();

        return new MethodInfo(scriptName, fullType, symbol.Name, paramTypes, returnType);
    }

    private static string MapType(ITypeSymbol type)
    {
        var name = type.ToDisplayString();
        return name switch
        {
            "int" => "int",
            "double" or "float" => "float",
            "string" => "string",
            "bool" => "bool",
            "void" => "void",
            _ when name.Contains("List<") => "Set<" + ExtractGenericArg(name) + ">",
            _ => name
        };
    }

    private static string GenerateRegistry(List<MethodInfo> methods)
    {
        if (methods.Count == 0) return "";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using HksScript.Interpreter;");
        sb.AppendLine();
        sb.AppendLine("public static partial class HksFuncRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static void RegisterAll(FunctionTable table)");
        sb.AppendLine("    {");

        foreach (var m in methods)
        {
            var casts = m.ParamTypes.Select((p, i) => $"({p})args[{i}]!").ToList();
            var args = string.Join(", ", casts);
            sb.AppendLine($"        table.Register(\"{m.ScriptName}\", new ExternalFunction(\"{m.ScriptName}\",");
            sb.AppendLine($"            args => {m.FullType}.{m.MethodName}({args})));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToSnakeCase(string name)
    {
        var sb = new StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            if (i > 0 && char.IsUpper(name[i]))
                sb.Append('_');
            sb.Append(char.ToLower(name[i]));
        }
        return sb.ToString();
    }

    private static string ExtractGenericArg(string type)
    {
        var start = type.IndexOf('<');
        var end = type.LastIndexOf('>');
        return start >= 0 && end > start ? type.Substring(start + 1, end - start - 1) : type;
    }

    private class MethodInfo
    {
        public string ScriptName { get; }
        public string FullType { get; }
        public string MethodName { get; }
        public string[] ParamTypes { get; }
        public string ReturnType { get; }
        public MethodInfo(string s, string t, string m, string[] p, string r)
        { ScriptName = s; FullType = t; MethodName = m; ParamTypes = p; ReturnType = r; }
    }
}
