//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/ayanami/HKSScript/HksScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HksScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IHksScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] HksScriptParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] HksScriptParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] HksScriptParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] HksScriptParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetStmt([NotNull] HksScriptParser.LetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetStmt([NotNull] HksScriptParser.LetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_([NotNull] HksScriptParser.Type_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_([NotNull] HksScriptParser.Type_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] HksScriptParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] HksScriptParser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>loadExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoadExpr([NotNull] HksScriptParser.LoadExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>loadExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoadExpr([NotNull] HksScriptParser.LoadExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarExpr([NotNull] HksScriptParser.VarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarExpr([NotNull] HksScriptParser.VarExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>methodCallExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCallExpr([NotNull] HksScriptParser.MethodCallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>methodCallExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCallExpr([NotNull] HksScriptParser.MethodCallExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>pipeExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPipeExpr([NotNull] HksScriptParser.PipeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>pipeExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPipeExpr([NotNull] HksScriptParser.PipeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] HksScriptParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] HksScriptParser.UnaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>addExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpr([NotNull] HksScriptParser.AddExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>addExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpr([NotNull] HksScriptParser.AddExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>literalExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralExpr([NotNull] HksScriptParser.LiteralExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>literalExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralExpr([NotNull] HksScriptParser.LiteralExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompExpr([NotNull] HksScriptParser.CompExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompExpr([NotNull] HksScriptParser.CompExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>mulExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulExpr([NotNull] HksScriptParser.MulExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>mulExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulExpr([NotNull] HksScriptParser.MulExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>queryExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQueryExpr([NotNull] HksScriptParser.QueryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>queryExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQueryExpr([NotNull] HksScriptParser.QueryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>callExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallExpr([NotNull] HksScriptParser.CallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>callExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallExpr([NotNull] HksScriptParser.CallExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] HksScriptParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] HksScriptParser.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] HksScriptParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] HksScriptParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondOr([NotNull] HksScriptParser.CondOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondOr([NotNull] HksScriptParser.CondOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondAnd([NotNull] HksScriptParser.CondAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondAnd([NotNull] HksScriptParser.CondAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condNot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondNot([NotNull] HksScriptParser.CondNotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condNot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondNot([NotNull] HksScriptParser.CondNotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condPrimary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondPrimary([NotNull] HksScriptParser.CondPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condPrimary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondPrimary([NotNull] HksScriptParser.CondPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] HksScriptParser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] HksScriptParser.ExprListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] HksScriptParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] HksScriptParser.LiteralContext context);
}
