//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HksScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HksScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IHksScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] HksScriptParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] HksScriptParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] HksScriptParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] HksScriptParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] HksScriptParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] HksScriptParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStmt([NotNull] HksScriptParser.ImportStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStmt([NotNull] HksScriptParser.ImportStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignStmt([NotNull] HksScriptParser.AssignStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignStmt([NotNull] HksScriptParser.AssignStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] HksScriptParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] HksScriptParser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] HksScriptParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] HksScriptParser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] HksScriptParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] HksScriptParser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.funcDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDef([NotNull] HksScriptParser.FuncDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.funcDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDef([NotNull] HksScriptParser.FuncDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] HksScriptParser.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] HksScriptParser.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] HksScriptParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] HksScriptParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_([NotNull] HksScriptParser.Type_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_([NotNull] HksScriptParser.Type_Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>pipeExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPipeExpr([NotNull] HksScriptParser.PipeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>pipeExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPipeExpr([NotNull] HksScriptParser.PipeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>intersectExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntersectExpr([NotNull] HksScriptParser.IntersectExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>intersectExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntersectExpr([NotNull] HksScriptParser.IntersectExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] HksScriptParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] HksScriptParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>diffExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiffExpr([NotNull] HksScriptParser.DiffExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>diffExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiffExpr([NotNull] HksScriptParser.DiffExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unionExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionExpr([NotNull] HksScriptParser.UnionExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unionExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionExpr([NotNull] HksScriptParser.UnionExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>queryCallExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQueryCallExpr([NotNull] HksScriptParser.QueryCallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>queryCallExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQueryCallExpr([NotNull] HksScriptParser.QueryCallExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] HksScriptParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] HksScriptParser.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarExpr([NotNull] HksScriptParser.VarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarExpr([NotNull] HksScriptParser.VarExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] HksScriptParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] HksScriptParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>addExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpr([NotNull] HksScriptParser.AddExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>addExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpr([NotNull] HksScriptParser.AddExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>queryFromExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQueryFromExpr([NotNull] HksScriptParser.QueryFromExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>queryFromExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQueryFromExpr([NotNull] HksScriptParser.QueryFromExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>literalExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralExpr([NotNull] HksScriptParser.LiteralExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>literalExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralExpr([NotNull] HksScriptParser.LiteralExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompExpr([NotNull] HksScriptParser.CompExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompExpr([NotNull] HksScriptParser.CompExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>mulExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulExpr([NotNull] HksScriptParser.MulExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>mulExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulExpr([NotNull] HksScriptParser.MulExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>callExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallExpr([NotNull] HksScriptParser.CallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>callExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallExpr([NotNull] HksScriptParser.CallExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] HksScriptParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] HksScriptParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompOp([NotNull] HksScriptParser.CompOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompOp([NotNull] HksScriptParser.CompOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddOp([NotNull] HksScriptParser.AddOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddOp([NotNull] HksScriptParser.AddOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulOp([NotNull] HksScriptParser.MulOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulOp([NotNull] HksScriptParser.MulOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] HksScriptParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] HksScriptParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondOr([NotNull] HksScriptParser.CondOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondOr([NotNull] HksScriptParser.CondOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondAnd([NotNull] HksScriptParser.CondAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondAnd([NotNull] HksScriptParser.CondAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condNot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondNot([NotNull] HksScriptParser.CondNotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condNot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondNot([NotNull] HksScriptParser.CondNotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condPrimary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondPrimary([NotNull] HksScriptParser.CondPrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condPrimary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondPrimary([NotNull] HksScriptParser.CondPrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] HksScriptParser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] HksScriptParser.ExprListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] HksScriptParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] HksScriptParser.LiteralContext context);
}
