//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HksScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IHksScriptListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class HksScriptBaseListener : IHksScriptListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] HksScriptParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] HksScriptParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] HksScriptParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] HksScriptParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] HksScriptParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] HksScriptParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.importStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStmt([NotNull] HksScriptParser.ImportStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.importStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStmt([NotNull] HksScriptParser.ImportStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignStmt([NotNull] HksScriptParser.AssignStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignStmt([NotNull] HksScriptParser.AssignStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStmt([NotNull] HksScriptParser.ExprStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStmt([NotNull] HksScriptParser.ExprStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] HksScriptParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] HksScriptParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDef([NotNull] HksScriptParser.FuncDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDef([NotNull] HksScriptParser.FuncDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamList([NotNull] HksScriptParser.ParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamList([NotNull] HksScriptParser.ParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] HksScriptParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] HksScriptParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_([NotNull] HksScriptParser.Type_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_([NotNull] HksScriptParser.Type_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>pipeExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPipeExpr([NotNull] HksScriptParser.PipeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>pipeExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPipeExpr([NotNull] HksScriptParser.PipeExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>intersectExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntersectExpr([NotNull] HksScriptParser.IntersectExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>intersectExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntersectExpr([NotNull] HksScriptParser.IntersectExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] HksScriptParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] HksScriptParser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unionExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionExpr([NotNull] HksScriptParser.UnionExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unionExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionExpr([NotNull] HksScriptParser.UnionExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] HksScriptParser.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] HksScriptParser.ParenExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarExpr([NotNull] HksScriptParser.VarExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarExpr([NotNull] HksScriptParser.VarExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpr([NotNull] HksScriptParser.NotExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpr([NotNull] HksScriptParser.NotExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>addExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddExpr([NotNull] HksScriptParser.AddExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>addExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddExpr([NotNull] HksScriptParser.AddExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>queryFromExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQueryFromExpr([NotNull] HksScriptParser.QueryFromExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>queryFromExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQueryFromExpr([NotNull] HksScriptParser.QueryFromExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>literalExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralExpr([NotNull] HksScriptParser.LiteralExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>literalExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralExpr([NotNull] HksScriptParser.LiteralExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompExpr([NotNull] HksScriptParser.CompExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompExpr([NotNull] HksScriptParser.CompExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>mulExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulExpr([NotNull] HksScriptParser.MulExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>mulExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulExpr([NotNull] HksScriptParser.MulExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>callExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallExpr([NotNull] HksScriptParser.CallExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>callExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallExpr([NotNull] HksScriptParser.CallExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] HksScriptParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] HksScriptParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] HksScriptParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] HksScriptParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondOr([NotNull] HksScriptParser.CondOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondOr([NotNull] HksScriptParser.CondOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondAnd([NotNull] HksScriptParser.CondAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondAnd([NotNull] HksScriptParser.CondAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondNot([NotNull] HksScriptParser.CondNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondNot([NotNull] HksScriptParser.CondNotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.condPrimary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondPrimary([NotNull] HksScriptParser.CondPrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.condPrimary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondPrimary([NotNull] HksScriptParser.CondPrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprList([NotNull] HksScriptParser.ExprListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprList([NotNull] HksScriptParser.ExprListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HksScriptParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] HksScriptParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HksScriptParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] HksScriptParser.LiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
