//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HksScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="HksScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IHksScriptVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] HksScriptParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] HksScriptParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] HksScriptParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStmt([NotNull] HksScriptParser.ImportStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStmt([NotNull] HksScriptParser.AssignStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprStmt([NotNull] HksScriptParser.ExprStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] HksScriptParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] HksScriptParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.funcDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDef([NotNull] HksScriptParser.FuncDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] HksScriptParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] HksScriptParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_([NotNull] HksScriptParser.Type_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pipeExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPipeExpr([NotNull] HksScriptParser.PipeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>intersectExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntersectExpr([NotNull] HksScriptParser.IntersectExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] HksScriptParser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>diffExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiffExpr([NotNull] HksScriptParser.DiffExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unionExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnionExpr([NotNull] HksScriptParser.UnionExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>queryCallExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQueryCallExpr([NotNull] HksScriptParser.QueryCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] HksScriptParser.ParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>varExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarExpr([NotNull] HksScriptParser.VarExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpr([NotNull] HksScriptParser.NotExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>addExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExpr([NotNull] HksScriptParser.AddExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>queryFromExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQueryFromExpr([NotNull] HksScriptParser.QueryFromExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>literalExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExpr([NotNull] HksScriptParser.LiteralExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompExpr([NotNull] HksScriptParser.CompExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>mulExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulExpr([NotNull] HksScriptParser.MulExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>callExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallExpr([NotNull] HksScriptParser.CallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="HksScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] HksScriptParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompOp([NotNull] HksScriptParser.CompOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOp([NotNull] HksScriptParser.AddOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulOp([NotNull] HksScriptParser.MulOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] HksScriptParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.condOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondOr([NotNull] HksScriptParser.CondOrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.condAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondAnd([NotNull] HksScriptParser.CondAndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.condNot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondNot([NotNull] HksScriptParser.CondNotContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.condPrimary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondPrimary([NotNull] HksScriptParser.CondPrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprList([NotNull] HksScriptParser.ExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HksScriptParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] HksScriptParser.LiteralContext context);
}
